apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: leooliveira1159/gitopsfc
  newTag: 8f7ff1c01ba917bc2c08821985398b2e28e4c91d
